### ISSUE TITLE
Use of Sass indented syntax

### ISSUE THREAD

**Issue by whatyouhide** [thoughtbot/guides#156]
I recently tried to organize my stylesheets workflow which has always been somehow messy. I stumbled upon some posts which promoted the idea of using SCSS for non-CSS-outputting code (`@mixins`, `%placeholders`, `$variables`) while using Sass (indent syntax) for everything that ouputs CSS.

So the logically resulting project structure I used has been this:

```
stylesheets/
  modules/
    header/
    main-nav/
    footer/
      _mixins.scss
      _variables.scss
      _footer.sass
  _variables.scss
  _placeholders.scss
  _mixins.scss
  application.scss # only @import statements
```

This is nice since I can write mixins, functions and placeholders more carefully and in a more structured way. For example, I can use one line blocks like

``` scss
@mixin box-sizing($type) {
  -webkit-box-sizing { box-sizing: $type }
  -mox-box-sizing { box-sizing: $type }
  box-sizing { box-sizing: $type }
}
```

which is way clearer then using _three_ lines per vendor prefix.

Writing actual CSS-outputting code in Sass has its advantages too.
For example I can `@include` mixins using using just `+`. Without having to write `{};` everywhere, I feel more proficent and the resulting code looks cleaner to me.

Also, this helps with separation of logic (`.scss`) and presentation (`.sass`).

What do you think? I'm curious about this technique.
