### ISSUE TITLE
Sass style guide order

### ISSUE THREAD

**Issue by maya** [thoughtbot/guides#374]
Firstly, I think the the Sass style guide is really great!

I have a quick question about "order" that I'm trying to figure out for 18F's coding styleguide. 

If you are using @includes for media queries, is that considered an @include that you'd put in the begining of the declaration or would you consider it as a media query, so it goes later on.  

Cc: @tysongach

**Comment by tysongach** [comment]
Hi @maya!

Great question. We typically treat these `@include`’s from Neat—`@include media($small-screen)`— as a standard media query, rather than a Sass `@include`. So they would be sorted directly after the declaration list:

```scss
.class-one {
  @include mixin;
  background-color: $color-variable;
  border: 0;

  @include media($small-screen) {
    margin: ($spacing-variable * 2) 1rem;
  }

  &::before {
    content: "hello";
  }
}
```

I bet we could make this more clear here in the guides…
